/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package milas_andmetric_gastronomi_mod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import milas_andmetric_gastronomi_mod.item.*;

import milas_andmetric_gastronomi_mod.MilasAndMetricGastronomyModMod;

import java.util.function.Function;

public class MilasAndMetricGastronomyModModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(MilasAndMetricGastronomyModMod.MODID);
	public static final DeferredItem<Item> MESADEGATRONOMIA;
	public static final DeferredItem<Item> TAMAL;
	public static final DeferredItem<Item> RAVIOLI;
	public static final DeferredItem<Item> JUGODEMANZANA;
	public static final DeferredItem<Item> SALSA;
	public static final DeferredItem<Item> CARTONDEPAPAS;
	public static final DeferredItem<Item> PAPASFRITAS;
	public static final DeferredItem<Item> PINCHOS;
	public static final DeferredItem<Item> SALSAMILAS;
	public static final DeferredItem<Item> RAVIOLIMILAS;
	public static final DeferredItem<Item> JUGOMETRIC;
	public static final DeferredItem<Item> SHUSHI;
	public static final DeferredItem<Item> TAMALOTE;
	public static final DeferredItem<Item> GALLETA_XD;
	public static final DeferredItem<Item> TAZADECAFE;
	public static final DeferredItem<Item> CAFEDOBBY;
	public static final DeferredItem<Item> GRANODECAFE;
	public static final DeferredItem<Item> RODAJADEPAN;
	public static final DeferredItem<Item> SANDWICH;
	public static final DeferredItem<Item> SANDWICHJULIAN;
	public static final DeferredItem<Item> RO;
	public static final DeferredItem<Item> TOMATE;
	public static final DeferredItem<Item> CUPCAKE_MARIAJOSE;
	public static final DeferredItem<Item> PAPELDECUPCAKE_MAJO;
	public static final DeferredItem<Item> ARANDANO;
	public static final DeferredItem<Item> VINOMOXTWZL;
	public static final DeferredItem<Item> UVAS;
	public static final DeferredItem<Item> UVASBLANCAS;
	public static final DeferredItem<Item> CUBETADEUVAS;
	public static final DeferredItem<Item> CUBETADEUVASBLANCAS;
	public static final DeferredItem<Item> VINOMOXZTWL;
	public static final DeferredItem<Item> OP;
	public static final DeferredItem<Item> MEGARAVIOLIMILAS;
	public static final DeferredItem<Item> CAF;
	public static final DeferredItem<Item> CUPA;
	public static final DeferredItem<Item> VINOBE;
	public static final DeferredItem<Item> SALSAMILASFLU_BUCKET;
	public static final DeferredItem<Item> GASTRONOMIWORLD;
	public static final DeferredItem<Item> RAMEN;
	public static final DeferredItem<Item> SOPADELRAMEN;
	public static final DeferredItem<Item> FIDEOS;
	public static final DeferredItem<Item> QUESO_1;
	public static final DeferredItem<Item> MASA;
	public static final DeferredItem<Item> PIZZA_1;
	public static final DeferredItem<Item> PIEDRACONTOMATE;
	public static final DeferredItem<Item> PANQUEQUE;
	public static final DeferredItem<Item> HAMBURGUESAJULIAN;
	public static final DeferredItem<Item> JUGOMETRICDEFINITIVO;
	public static final DeferredItem<Item> RAVIOLIMILASDEFINITIVO;
	public static final DeferredItem<Item> AA_ARMOR_HELMET;
	public static final DeferredItem<Item> AA_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AA_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AA_ARMOR_BOOTS;
	public static final DeferredItem<Item> ARROZ;
	public static final DeferredItem<Item> BOLSADEARROZ;
	public static final DeferredItem<Item> CAFE;
	public static final DeferredItem<Item> SAL_DUST;
	public static final DeferredItem<Item> SAL_ORE;
	public static final DeferredItem<Item> SAL_BLOCK;
	public static final DeferredItem<Item> PANQUEQUES;
	public static final DeferredItem<Item> PIMIENTA;
	public static final DeferredItem<Item> SALSAMETRIC;
	public static final DeferredItem<Item> SALSAMETRICFLU_BUCKET;
	public static final DeferredItem<Item> ESPAGUETI;
	public static final DeferredItem<Item> ALBONDIGA;
	public static final DeferredItem<Item> HELADODOBBY;
	public static final DeferredItem<Item> HIELOTRITURADO;
	public static final DeferredItem<Item> RAVIOLIMILASARM_PICKAXE;
	public static final DeferredItem<Item> RAVIOLIMILASARM_AXE;
	public static final DeferredItem<Item> RAVIOLIMILASARM_SWORD;
	public static final DeferredItem<Item> RAVIOLIMILASARM_SHOVEL;
	public static final DeferredItem<Item> RAVIOLIMILASARM_HOE;
	public static final DeferredItem<Item> BLOQUEMILAS;
	public static final DeferredItem<Item> MUNDOMILAS;
	public static final DeferredItem<Item> M_SPAWN_EGG;
	public static final DeferredItem<Item> HELADODOBBYNIGER;
	public static final DeferredItem<Item> TINTEBLACK;
	public static final DeferredItem<Item> SALSAMETRICN;
	public static final DeferredItem<Item> HAMBUGESAN;
	public static final DeferredItem<Item> ALBONDIGAN;
	public static final DeferredItem<Item> PANQUEQUESN;
	public static final DeferredItem<Item> X_2;
	public static final DeferredItem<Item> ESPAN;
	public static final DeferredItem<Item> TAMALOTEN;
	public static final DeferredItem<Item> SALSAMILASN;
	public static final DeferredItem<Item> SALSAN;
	public static final DeferredItem<Item> CARTONN;
	public static final DeferredItem<Item> PAN;
	public static final DeferredItem<Item> PANN;
	public static final DeferredItem<Item> RON;
	public static final DeferredItem<Item> RAMENN;
	public static final DeferredItem<Item> X_2N;
	public static final DeferredItem<Item> XDN;
	public static final DeferredItem<Item> OPN;
	public static final DeferredItem<Item> METRICN;
	public static final DeferredItem<Item> JUGOMETRIOCN;
	public static final DeferredItem<Item> SHUSHIN;
	public static final DeferredItem<Item> PIEN;
	public static final DeferredItem<Item> PIZZAN;
	public static final DeferredItem<Item> MILASN;
	public static final DeferredItem<Item> MILASNN;
	public static final DeferredItem<Item> MILASNNN;
	public static final DeferredItem<Item> EEARMOR_HELMET;
	public static final DeferredItem<Item> EEARMOR_CHESTPLATE;
	public static final DeferredItem<Item> EEARMOR_LEGGINGS;
	public static final DeferredItem<Item> EEARMOR_BOOTS;
	public static final DeferredItem<Item> HUEVO_ARMOR_HELMET;
	public static final DeferredItem<Item> HUEVO_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> HUEVO_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> HUEVO_ARMOR_BOOTS;
	public static final DeferredItem<Item> SOYEXTRAHUEVOORDINARIO;
	public static final DeferredItem<Item> NADA;
	public static final DeferredItem<Item> PANDEPERRO;
	public static final DeferredItem<Item> COCACOLA;
	public static final DeferredItem<Item> COCAPINA;
	public static final DeferredItem<Item> JULIANCOLA;
	public static final DeferredItem<Item> PIZZAMILAS;
	public static final DeferredItem<Item> JUGODESANDIA;
	public static final DeferredItem<Item> JUGODEZANAHORIA;
	public static final DeferredItem<Item> SOPADETOMATE;
	public static final DeferredItem<Item> MD;
	public static final DeferredItem<Item> TA;
	public static final DeferredItem<Item> PINA;
	public static final DeferredItem<Item> AGUACATE;
	public static final DeferredItem<Item> LIMON;
	public static final DeferredItem<Item> LIMONADA;
	public static final DeferredItem<Item> SALCHICHA;
	public static final DeferredItem<Item> JUGO_1;
	public static final DeferredItem<Item> NARANA;
	public static final DeferredItem<Item> COCANAJA;
	public static final DeferredItem<Item> MILASCOLA;
	public static final DeferredItem<Item> S_GUACAPIDER_SPAWN_EGG;
	public static final DeferredItem<Item> GUACAMOLE;
	public static final DeferredItem<Item> PERROCALIENTEA;
	public static final DeferredItem<Item> PIZACONPUNA;
	public static final DeferredItem<Item> X_3;
	public static final DeferredItem<Item> HAMBURGUESA;
	public static final DeferredItem<Item> CCOPADEVINO;
	public static final DeferredItem<Item> COPA;
	public static final DeferredItem<Item> REYNAGUACA_SPAWN_EGG;
	public static final DeferredItem<Item> PALTA_WOOD;
	public static final DeferredItem<Item> PALTA_LOG;
	public static final DeferredItem<Item> PALTA_PLANKS;
	public static final DeferredItem<Item> PALTA_LEAVES;
	public static final DeferredItem<Item> PALTA_STAIRS;
	public static final DeferredItem<Item> PALTA_SLAB;
	public static final DeferredItem<Item> PALTA_FENCE;
	public static final DeferredItem<Item> PALTA_FENCE_GATE;
	public static final DeferredItem<Item> PALTA_PRESSURE_PLATE;
	public static final DeferredItem<Item> PALTA_BUTTON;
	public static final DeferredItem<Item> CPLAMETRUIC;
	public static final DeferredItem<Item> PASTAMILAS;
	public static final DeferredItem<Item> MILAS;
	public static final DeferredItem<Item> GUACAPIG_SPAWN_EGG;
	public static final DeferredItem<Item> CUPC;
	public static final DeferredItem<Item> A_12A;
	public static final DeferredItem<Item> PERROPITUFO;
	public static final DeferredItem<Item> OLLITA_SPAWN_EGG;
	public static final DeferredItem<Item> PIEDELIMON;
	public static final DeferredItem<Item> OLLITACCHULE_SPAWN_EGG;
	public static final DeferredItem<Item> BURBUJITO_SPAWN_EGG;
	public static final DeferredItem<Item> JAMON_SPAWN_EGG;
	public static final DeferredItem<Item> JAMONA;
	public static final DeferredItem<Item> SANDWICHLEJENDARIO;
	public static final DeferredItem<Item> CHEF_SPAWN_EGG;
	public static final DeferredItem<Item> SOPAJULIAN;
	public static final DeferredItem<Item> GOMITA;
	public static final DeferredItem<Item> CUPK;
	public static final DeferredItem<Item> PIZZADECAMMARON;
	public static final DeferredItem<Item> SHUSI;
	public static final DeferredItem<Item> A_13A;
	public static final DeferredItem<Item> COCAMANZ;
	public static final DeferredItem<Item> AGUACATEENCANTADO;
	public static final DeferredItem<Item> TOMATEDORADO;
	public static final DeferredItem<Item> GUACAMOLEREAL;
	public static final DeferredItem<Item> MAYONESA;
	public static final DeferredItem<Item> MANTEQUILLA;
	public static final DeferredItem<Item> CEBOLLA;
	public static final DeferredItem<Item> SALSATARTARA;
	public static final DeferredItem<Item> CHILE;
	public static final DeferredItem<Item> CHILEFANTASMA;
	public static final DeferredItem<Item> CHILEGELIDO;
	public static final DeferredItem<Item> CRISTAL_HELADO_INGOT;
	public static final DeferredItem<Item> CRISTAL_HELADO_ORE;
	public static final DeferredItem<Item> CRISTAL_HELADO_BLOCK;
	public static final DeferredItem<Item> TANQUECRIOGENICO;
	public static final DeferredItem<Item> MILASCHEF_SPAWN_EGG;
	public static final DeferredItem<Item> CUCHILLO;
	public static final DeferredItem<Item> CURRY;
	public static final DeferredItem<Item> TACO;
	public static final DeferredItem<Item> BURRITO;
	public static final DeferredItem<Item> TORTILLA;
	public static final DeferredItem<Item> TACOCONCHILEFANTASMA;
	public static final DeferredItem<Item> BURRITOFANTASMA;
	public static final DeferredItem<Item> CURRYFANTASMA;
	public static final DeferredItem<Item> TACOGELIDO;
	public static final DeferredItem<Item> BURRIGELIDO;
	public static final DeferredItem<Item> CURRYGELIDO;
	public static final DeferredItem<Item> DONA;
	public static final DeferredItem<Item> DONAMILAS;
	public static final DeferredItem<Item> GLACEADOITEM;
	public static final DeferredItem<Item> DONASINGLASEADO;
	public static final DeferredItem<Item> GLACEADOMILAS;
	public static final DeferredItem<Item> CRISTALDE_CARAMELO_INGOT;
	public static final DeferredItem<Item> CRISTALDE_CARAMELO_ORE;
	public static final DeferredItem<Item> CRISTALDE_CARAMELO_BLOCK;
	public static final DeferredItem<Item> CRISTALDECARAMMELO;
	public static final DeferredItem<Item> OSODEGOMA_SPAWN_EGG;
	public static final DeferredItem<Item> DONANIGHTMER;
	public static final DeferredItem<Item> A_3436756D;
	public static final DeferredItem<Item> CARAMELO;
	public static final DeferredItem<Item> MACARON;
	public static final DeferredItem<Item> MACARONJULIAN;
	public static final DeferredItem<Item> MACARONRADIOACTIVO;
	public static final DeferredItem<Item> HELADOMILAS;
	public static final DeferredItem<Item> G_UARDIAGUACA_SPAWN_EGG;
	public static final DeferredItem<Item> OSITO_2_SPAWN_EGG;
	public static final DeferredItem<Item> OSITO_3_SPAWN_EGG;
	public static final DeferredItem<Item> OSITO_4_SPAWN_EGG;
	public static final DeferredItem<Item> OSITO_5_SPAWN_EGG;
	public static final DeferredItem<Item> SALMISTICAS_DUST;
	public static final DeferredItem<Item> SALMISTICAS_ORE;
	public static final DeferredItem<Item> SALMISTICAS_BLOCK;
	public static final DeferredItem<Item> HELADO;
	public static final DeferredItem<Item> GOMITA_2;
	public static final DeferredItem<Item> GOMITA_3;
	public static final DeferredItem<Item> GOMITA_4;
	public static final DeferredItem<Item> GOMITA_5;
	public static final DeferredItem<Item> PERRONIGTHMER;
	public static final DeferredItem<Item> NAITBEAR_SPAWN_EGG;
	public static final DeferredItem<Item> SAL_2;
	public static final DeferredItem<Item> GUMMYBEAR;
	public static final DeferredItem<Item> PINCHOCOMPLETO;
	public static final DeferredItem<Item> CRISTALFUNDIDO;
	public static final DeferredItem<Item> CHILEPESADILLA;
	public static final DeferredItem<Item> HADA_DEDULCE_SPAWN_EGG;
	public static final DeferredItem<Item> CORRINPOPPER_SPAWN_EGG;
	public static final DeferredItem<Item> SWETIPOPPER_SPAWN_EGG;
	public static final DeferredItem<Item> CORRINMETRIC_SPAWN_EGG;
	public static final DeferredItem<Item> CUCHILLOFUN;
	public static final DeferredItem<Item> DUMPLINGS;
	public static final DeferredItem<Item> TEDEBOBA;
	public static final DeferredItem<Item> TEDEBOBAMETRIC;
	public static final DeferredItem<Item> BANANASPLIT;
	public static final DeferredItem<Item> BANANA;
	public static final DeferredItem<Item> SEMILLADEBOBA;
	public static final DeferredItem<Item> BOBALIQUIDA;
	public static final DeferredItem<Item> DUMPLINGVENDEDORDEBOBA_SPAWN_EGG;
	public static final DeferredItem<Item> DUMPLINPEQUENO_SPAWN_EGG;
	public static final DeferredItem<Item> DUMPLINGMEDIANO_SPAWN_EGG;
	public static final DeferredItem<Item> DUMPLINGRANDE_SPAWN_EGG;
	public static final DeferredItem<Item> CALAMARFRITO_SPAWN_EGG;
	public static final DeferredItem<Item> SANDWICHSALVAJE_SPAWN_EGG;
	public static final DeferredItem<Item> DURIAN;
	public static final DeferredItem<Item> CUBANO_SPAWN_EGG;
	public static final DeferredItem<Item> SATAANDAGUI;
	public static final DeferredItem<Item> CONODEHELADO_2;
	public static final DeferredItem<Item> SATAANDAGI;
	public static final DeferredItem<Item> GRANADILLAROJA;
	public static final DeferredItem<Item> BAOZI;
	public static final DeferredItem<Item> YAKI_ONIGIRI;
	public static final DeferredItem<Item> SANDWICHDULCE_SPAWN_EGG;
	public static final DeferredItem<Item> ZONGZI;
	public static final DeferredItem<Item> BOLADESESAMO;
	public static final DeferredItem<Item> GREENGRAPES;
	public static final DeferredItem<Item> PURPLEONION;
	public static final DeferredItem<Item> WHITEONION;
	public static final DeferredItem<Item> GOMITA_6;
	public static final DeferredItem<Item> LETTUCE;
	public static final DeferredItem<Item> TOMATO_STAGE_0;
	public static final DeferredItem<Item> TOMATO_STAGE_1;
	public static final DeferredItem<Item> TOMATO_STAGE_2;
	public static final DeferredItem<Item> TOMATO_STAGE_3;
	public static final DeferredItem<Item> CANDYGRASS;
	public static final DeferredItem<Item> CANDYBARPLANT;
	public static final DeferredItem<Item> OSO_6_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_2_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_3_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_4_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_5_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_6_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_7_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_8_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMETRIC_SPAWN_EGG;
	public static final DeferredItem<Item> SLIME_SPAWN_EGG;
	public static final DeferredItem<Item> DONASANGUIJUELA_SPAWN_EGG;
	public static final DeferredItem<Item> PHATOMPALETA_SPAWN_EGG;
	public static final DeferredItem<Item> PHATOMPALETA_2_SPAWN_EGG;
	public static final DeferredItem<Item> JARRON_SPAWN_EGG;
	public static final DeferredItem<Item> JARRONJULIAN_SPAWN_EGG;
	public static final DeferredItem<Item> SMORE_SPAWN_EGG;
	public static final DeferredItem<Item> SMOREVOLADOR_SPAWN_EGG;
	public static final DeferredItem<Item> ARANAHAMBURGUESA_SPAWN_EGG;
	public static final DeferredItem<Item> SERPIENTEHELADO_SPAWN_EGG;
	public static final DeferredItem<Item> PANDEPERRONAITMER;
	public static final DeferredItem<Item> HELADO_1;
	public static final DeferredItem<Item> HELADO_2;
	public static final DeferredItem<Item> HELADO_3;
	public static final DeferredItem<Item> HELADO_4;
	public static final DeferredItem<Item> HELADO_5;
	public static final DeferredItem<Item> HELADO_6;
	public static final DeferredItem<Item> HELADO_7;
	public static final DeferredItem<Item> PALETA_1;
	public static final DeferredItem<Item> PALETA_2;
	public static final DeferredItem<Item> SMORECOMIDA;
	public static final DeferredItem<Item> SMORE_2;
	public static final DeferredItem<Item> CORN;
	public static final DeferredItem<Item> SWEETCORN;
	public static final DeferredItem<Item> DUMPLINGIGANTE_SPAWN_EGG;
	public static final DeferredItem<Item> GRANDDUMPLING;
	public static final DeferredItem<Item> BLOQUESERPIENTE;
	public static final DeferredItem<Item> ESTATUANAITBEAR;
	public static final DeferredItem<Item> MALTEADITO_SPAWN_EGG;
	public static final DeferredItem<Item> CUPKAQUEMAJODEFINITIVO;
	public static final DeferredItem<Item> CEREZA;
	public static final DeferredItem<Item> CEREZADULCE;
	public static final DeferredItem<Item> MALTEADA;
	public static final DeferredItem<Item> MALTEADAMETRIC;
	public static final DeferredItem<Item> CREMABATIDA;
	public static final DeferredItem<Item> PIZZACONGELADA;
	static {
		MESADEGATRONOMIA = block(MilasAndMetricGastronomyModModBlocks.MESADEGATRONOMIA);
		TAMAL = register("tamal", TamalItem::new);
		RAVIOLI = register("ravioli", RavioliItem::new);
		JUGODEMANZANA = register("jugodemanzana", JugodemanzanaItem::new);
		SALSA = register("salsa", SalsaItem::new);
		CARTONDEPAPAS = register("cartondepapas", CartondepapasItem::new);
		PAPASFRITAS = register("papasfritas", PapasfritasItem::new);
		PINCHOS = register("pinchos", PinchosItem::new);
		SALSAMILAS = register("salsamilas", SalsamilasItem::new);
		RAVIOLIMILAS = register("raviolimilas", RaviolimilasItem::new);
		JUGOMETRIC = register("jugometric", JugometricItem::new);
		SHUSHI = register("shushi", ShushiItem::new);
		TAMALOTE = register("tamalote", TamaloteItem::new);
		GALLETA_XD = register("galleta_xd", GalletaXDItem::new);
		TAZADECAFE = register("tazadecafe", TazadecafeItem::new);
		CAFEDOBBY = register("cafedobby", CafedobbyItem::new);
		GRANODECAFE = register("granodecafe", GranodecafeItem::new);
		RODAJADEPAN = register("rodajadepan", RodajadepanItem::new);
		SANDWICH = register("sandwich", SandwichItem::new);
		SANDWICHJULIAN = register("sandwichjulian", SandwichjulianItem::new);
		RO = register("ro", RoItem::new);
		TOMATE = register("tomate", TomateItem::new);
		CUPCAKE_MARIAJOSE = register("cupcake_mariajose", CupcakeMariajoseItem::new);
		PAPELDECUPCAKE_MAJO = register("papeldecupcake_majo", PapeldecupcakeMajoItem::new);
		ARANDANO = register("arandano", ArandanoItem::new);
		VINOMOXTWZL = register("vinomoxtwzl", VinomoxtwzlItem::new);
		UVAS = register("uvas", UvasItem::new);
		UVASBLANCAS = register("uvasblancas", UvasblancasItem::new);
		CUBETADEUVAS = register("cubetadeuvas", CubetadeuvasItem::new);
		CUBETADEUVASBLANCAS = register("cubetadeuvasblancas", CubetadeuvasblancasItem::new);
		VINOMOXZTWL = register("vinomoxztwl", VinomoxztwlItem::new);
		OP = register("op", OpItem::new);
		MEGARAVIOLIMILAS = register("megaraviolimilas", MegaraviolimilasItem::new);
		CAF = register("caf", CafItem::new);
		CUPA = register("cupa", CupaItem::new);
		VINOBE = register("vinobe", VinobeItem::new);
		SALSAMILASFLU_BUCKET = register("salsamilasflu_bucket", SalsamilasfluItem::new);
		GASTRONOMIWORLD = register("gastronomiworld", GastronomiworldItem::new);
		RAMEN = register("ramen", RamenItem::new);
		SOPADELRAMEN = register("sopadelramen", SopadelramenItem::new);
		FIDEOS = register("fideos", FideosItem::new);
		QUESO_1 = register("queso_1", Queso1Item::new);
		MASA = register("masa", MasaItem::new);
		PIZZA_1 = register("pizza_1", Pizza1Item::new);
		PIEDRACONTOMATE = register("piedracontomate", PiedracontomateItem::new);
		PANQUEQUE = register("panqueque", PanquequeItem::new);
		HAMBURGUESAJULIAN = register("hamburguesajulian", HamburguesajulianItem::new);
		JUGOMETRICDEFINITIVO = register("jugometricdefinitivo", JugometricdefinitivoItem::new);
		RAVIOLIMILASDEFINITIVO = register("raviolimilasdefinitivo", RaviolimilasdefinitivoItem::new);
		AA_ARMOR_HELMET = register("aa_armor_helmet", AaArmorItem.Helmet::new);
		AA_ARMOR_CHESTPLATE = register("aa_armor_chestplate", AaArmorItem.Chestplate::new);
		AA_ARMOR_LEGGINGS = register("aa_armor_leggings", AaArmorItem.Leggings::new);
		AA_ARMOR_BOOTS = register("aa_armor_boots", AaArmorItem.Boots::new);
		ARROZ = register("arroz", ArrozItem::new);
		BOLSADEARROZ = register("bolsadearroz", BolsadearrozItem::new);
		CAFE = register("cafe", CafeItem::new);
		SAL_DUST = register("sal_dust", SalDustItem::new);
		SAL_ORE = block(MilasAndMetricGastronomyModModBlocks.SAL_ORE);
		SAL_BLOCK = block(MilasAndMetricGastronomyModModBlocks.SAL_BLOCK);
		PANQUEQUES = register("panqueques", PanquequesItem::new);
		PIMIENTA = register("pimienta", PimientaItem::new);
		SALSAMETRIC = register("salsametric", SalsametricItem::new);
		SALSAMETRICFLU_BUCKET = register("salsametricflu_bucket", SalsametricfluItem::new);
		ESPAGUETI = register("espagueti", EspaguetiItem::new);
		ALBONDIGA = register("albondiga", AlbondigaItem::new);
		HELADODOBBY = register("heladodobby", HeladodobbyItem::new);
		HIELOTRITURADO = register("hielotriturado", HielotrituradoItem::new);
		RAVIOLIMILASARM_PICKAXE = register("raviolimilasarm_pickaxe", RaviolimilasarmPickaxeItem::new);
		RAVIOLIMILASARM_AXE = register("raviolimilasarm_axe", RaviolimilasarmAxeItem::new);
		RAVIOLIMILASARM_SWORD = register("raviolimilasarm_sword", RaviolimilasarmSwordItem::new);
		RAVIOLIMILASARM_SHOVEL = register("raviolimilasarm_shovel", RaviolimilasarmShovelItem::new);
		RAVIOLIMILASARM_HOE = register("raviolimilasarm_hoe", RaviolimilasarmHoeItem::new);
		BLOQUEMILAS = block(MilasAndMetricGastronomyModModBlocks.BLOQUEMILAS);
		MUNDOMILAS = register("mundomilas", MundomilasItem::new);
		M_SPAWN_EGG = register("m_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.M.get(), properties));
		HELADODOBBYNIGER = register("heladodobbyniger", HeladodobbynigerItem::new);
		TINTEBLACK = register("tinteblack", TinteblackItem::new);
		SALSAMETRICN = register("salsametricn", SalsametricnItem::new);
		HAMBUGESAN = register("hambugesan", HambugesanItem::new);
		ALBONDIGAN = register("albondigan", AlbondiganItem::new);
		PANQUEQUESN = register("panquequesn", PanquequesnItem::new);
		X_2 = register("x_2", X2Item::new);
		ESPAN = register("espan", EspanItem::new);
		TAMALOTEN = register("tamaloten", TamalotenItem::new);
		SALSAMILASN = register("salsamilasn", SalsamilasnItem::new);
		SALSAN = register("salsan", SalsanItem::new);
		CARTONN = register("cartonn", CartonnItem::new);
		PAN = register("pan", PanItem::new);
		PANN = register("pann", PannItem::new);
		RON = register("ron", RonItem::new);
		RAMENN = register("ramenn", RamennItem::new);
		X_2N = register("x_2n", X2nItem::new);
		XDN = register("xdn", XdnItem::new);
		OPN = register("opn", OpnItem::new);
		METRICN = register("metricn", MetricnItem::new);
		JUGOMETRIOCN = register("jugometriocn", JugometriocnItem::new);
		SHUSHIN = register("shushin", ShushinItem::new);
		PIEN = register("pien", PienItem::new);
		PIZZAN = register("pizzan", PizzanItem::new);
		MILASN = register("milasn", MilasnItem::new);
		MILASNN = register("milasnn", MilasnnItem::new);
		MILASNNN = register("milasnnn", MilasnnnItem::new);
		EEARMOR_HELMET = register("eearmor_helmet", EearmorItem.Helmet::new);
		EEARMOR_CHESTPLATE = register("eearmor_chestplate", EearmorItem.Chestplate::new);
		EEARMOR_LEGGINGS = register("eearmor_leggings", EearmorItem.Leggings::new);
		EEARMOR_BOOTS = register("eearmor_boots", EearmorItem.Boots::new);
		HUEVO_ARMOR_HELMET = register("huevo_armor_helmet", HuevoArmorItem.Helmet::new);
		HUEVO_ARMOR_CHESTPLATE = register("huevo_armor_chestplate", HuevoArmorItem.Chestplate::new);
		HUEVO_ARMOR_LEGGINGS = register("huevo_armor_leggings", HuevoArmorItem.Leggings::new);
		HUEVO_ARMOR_BOOTS = register("huevo_armor_boots", HuevoArmorItem.Boots::new);
		SOYEXTRAHUEVOORDINARIO = register("soyextrahuevoordinario", SoyextrahuevoordinarioItem::new);
		NADA = register("nada", NadaItem::new);
		PANDEPERRO = register("pandeperro", PandeperroItem::new);
		COCACOLA = register("cocacola", CocacolaItem::new);
		COCAPINA = register("cocapina", CocapinaItem::new);
		JULIANCOLA = register("juliancola", JuliancolaItem::new);
		PIZZAMILAS = register("pizzamilas", PizzamilasItem::new);
		JUGODESANDIA = register("jugodesandia", JugodesandiaItem::new);
		JUGODEZANAHORIA = register("jugodezanahoria", JugodezanahoriaItem::new);
		SOPADETOMATE = register("sopadetomate", SopadetomateItem::new);
		MD = register("md", MdItem::new);
		TA = register("ta", TaItem::new);
		PINA = register("pina", PinaItem::new);
		AGUACATE = register("aguacate", AguacateItem::new);
		LIMON = register("limon", LimonItem::new);
		LIMONADA = register("limonada", LimonadaItem::new);
		SALCHICHA = register("salchicha", SalchichaItem::new);
		JUGO_1 = register("jugo_1", Jugo1Item::new);
		NARANA = register("narana", NaranaItem::new);
		COCANAJA = register("cocanaja", CocanajaItem::new);
		MILASCOLA = register("milascola", MilascolaItem::new);
		S_GUACAPIDER_SPAWN_EGG = register("s_guacapider_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.S_GUACAPIDER.get(), properties));
		GUACAMOLE = register("guacamole", GuacamoleItem::new);
		PERROCALIENTEA = register("perrocalientea", PerrocalienteaItem::new);
		PIZACONPUNA = register("pizaconpuna", PizaconpunaItem::new);
		X_3 = register("x_3", X3Item::new);
		HAMBURGUESA = register("hamburguesa", HamburguesaItem::new);
		CCOPADEVINO = register("ccopadevino", CcopadevinoItem::new);
		COPA = register("copa", CopaItem::new);
		REYNAGUACA_SPAWN_EGG = register("reynaguaca_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.REYNAGUACA.get(), properties));
		PALTA_WOOD = block(MilasAndMetricGastronomyModModBlocks.PALTA_WOOD);
		PALTA_LOG = block(MilasAndMetricGastronomyModModBlocks.PALTA_LOG);
		PALTA_PLANKS = block(MilasAndMetricGastronomyModModBlocks.PALTA_PLANKS);
		PALTA_LEAVES = block(MilasAndMetricGastronomyModModBlocks.PALTA_LEAVES);
		PALTA_STAIRS = block(MilasAndMetricGastronomyModModBlocks.PALTA_STAIRS);
		PALTA_SLAB = block(MilasAndMetricGastronomyModModBlocks.PALTA_SLAB);
		PALTA_FENCE = block(MilasAndMetricGastronomyModModBlocks.PALTA_FENCE);
		PALTA_FENCE_GATE = block(MilasAndMetricGastronomyModModBlocks.PALTA_FENCE_GATE);
		PALTA_PRESSURE_PLATE = block(MilasAndMetricGastronomyModModBlocks.PALTA_PRESSURE_PLATE);
		PALTA_BUTTON = block(MilasAndMetricGastronomyModModBlocks.PALTA_BUTTON);
		CPLAMETRUIC = register("cplametruic", CplametruicItem::new);
		PASTAMILAS = register("pastamilas", PastamilasItem::new);
		MILAS = register("milas", MilasItem::new);
		GUACAPIG_SPAWN_EGG = register("guacapig_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.GUACAPIG.get(), properties));
		CUPC = register("cupc", CupcItem::new);
		A_12A = register("a_12a", A12aItem::new);
		PERROPITUFO = register("perropitufo", PerropitufoItem::new);
		OLLITA_SPAWN_EGG = register("ollita_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.OLLITA.get(), properties));
		PIEDELIMON = register("piedelimon", PiedelimonItem::new);
		OLLITACCHULE_SPAWN_EGG = register("ollitacchule_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.OLLITACCHULE.get(), properties));
		BURBUJITO_SPAWN_EGG = register("burbujito_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.BURBUJITO.get(), properties));
		JAMON_SPAWN_EGG = register("jamon_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.JAMON.get(), properties));
		JAMONA = register("jamona", JamonaItem::new);
		SANDWICHLEJENDARIO = register("sandwichlejendario", SandwichlejendarioItem::new);
		CHEF_SPAWN_EGG = register("chef_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.CHEF.get(), properties));
		SOPAJULIAN = register("sopajulian", SopajulianItem::new);
		GOMITA = register("gomita", GomitaItem::new);
		CUPK = register("cupk", CupkItem::new);
		PIZZADECAMMARON = register("pizzadecammaron", PizzadecammaronItem::new);
		SHUSI = register("shusi", ShusiItem::new);
		A_13A = register("a_13a", A13aItem::new);
		COCAMANZ = register("cocamanz", CocamanzItem::new);
		AGUACATEENCANTADO = register("aguacateencantado", AguacateencantadoItem::new);
		TOMATEDORADO = register("tomatedorado", TomatedoradoItem::new);
		GUACAMOLEREAL = register("guacamolereal", GuacamolerealItem::new);
		MAYONESA = register("mayonesa", MayonesaItem::new);
		MANTEQUILLA = register("mantequilla", MantequillaItem::new);
		CEBOLLA = register("cebolla", CebollaItem::new);
		SALSATARTARA = register("salsatartara", SalsatartaraItem::new);
		CHILE = register("chile", ChileItem::new);
		CHILEFANTASMA = register("chilefantasma", ChilefantasmaItem::new);
		CHILEGELIDO = register("chilegelido", ChilegelidoItem::new);
		CRISTAL_HELADO_INGOT = register("cristal_helado_ingot", CristalHeladoIngotItem::new);
		CRISTAL_HELADO_ORE = block(MilasAndMetricGastronomyModModBlocks.CRISTAL_HELADO_ORE);
		CRISTAL_HELADO_BLOCK = block(MilasAndMetricGastronomyModModBlocks.CRISTAL_HELADO_BLOCK);
		TANQUECRIOGENICO = register("tanquecriogenico", TanquecriogenicoItem::new);
		MILASCHEF_SPAWN_EGG = register("milaschef_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.MILASCHEF.get(), properties));
		CUCHILLO = register("cuchillo", CuchilloItem::new);
		CURRY = register("curry", CurryItem::new);
		TACO = register("taco", TacoItem::new);
		BURRITO = register("burrito", BurritoItem::new);
		TORTILLA = register("tortilla", TortillaItem::new);
		TACOCONCHILEFANTASMA = register("tacoconchilefantasma", TacoconchilefantasmaItem::new);
		BURRITOFANTASMA = register("burritofantasma", BurritofantasmaItem::new);
		CURRYFANTASMA = register("curryfantasma", CurryfantasmaItem::new);
		TACOGELIDO = register("tacogelido", TacogelidoItem::new);
		BURRIGELIDO = register("burrigelido", BurrigelidoItem::new);
		CURRYGELIDO = register("currygelido", CurrygelidoItem::new);
		DONA = register("dona", DonaItem::new);
		DONAMILAS = register("donamilas", DonamilasItem::new);
		GLACEADOITEM = register("glaceadoitem", GlaceadoitemItem::new);
		DONASINGLASEADO = register("donasinglaseado", DonasinglaseadoItem::new);
		GLACEADOMILAS = register("glaceadomilas", GlaceadomilasItem::new);
		CRISTALDE_CARAMELO_INGOT = register("cristalde_caramelo_ingot", CristaldeCarameloIngotItem::new);
		CRISTALDE_CARAMELO_ORE = block(MilasAndMetricGastronomyModModBlocks.CRISTALDE_CARAMELO_ORE);
		CRISTALDE_CARAMELO_BLOCK = block(MilasAndMetricGastronomyModModBlocks.CRISTALDE_CARAMELO_BLOCK);
		CRISTALDECARAMMELO = register("cristaldecarammelo", CristaldecarammeloItem::new);
		OSODEGOMA_SPAWN_EGG = register("osodegoma_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.OSODEGOMA.get(), properties));
		DONANIGHTMER = register("donanightmer", DonanightmerItem::new);
		A_3436756D = register("a_3436756d", A3436756dItem::new);
		CARAMELO = register("caramelo", CarameloItem::new);
		MACARON = register("macaron", MacaronItem::new);
		MACARONJULIAN = register("macaronjulian", MacaronjulianItem::new);
		MACARONRADIOACTIVO = register("macaronradioactivo", MacaronradioactivoItem::new);
		HELADOMILAS = register("heladomilas", HeladomilasItem::new);
		G_UARDIAGUACA_SPAWN_EGG = register("g_uardiaguaca_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.G_UARDIAGUACA.get(), properties));
		OSITO_2_SPAWN_EGG = register("osito_2_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.OSITO_2.get(), properties));
		OSITO_3_SPAWN_EGG = register("osito_3_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.OSITO_3.get(), properties));
		OSITO_4_SPAWN_EGG = register("osito_4_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.OSITO_4.get(), properties));
		OSITO_5_SPAWN_EGG = register("osito_5_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.OSITO_5.get(), properties));
		SALMISTICAS_DUST = register("salmisticas_dust", SalmisticasDustItem::new);
		SALMISTICAS_ORE = block(MilasAndMetricGastronomyModModBlocks.SALMISTICAS_ORE);
		SALMISTICAS_BLOCK = block(MilasAndMetricGastronomyModModBlocks.SALMISTICAS_BLOCK);
		HELADO = register("helado", HeladoItem::new);
		GOMITA_2 = register("gomita_2", Gomita2Item::new);
		GOMITA_3 = register("gomita_3", Gomita3Item::new);
		GOMITA_4 = register("gomita_4", Gomita4Item::new);
		GOMITA_5 = register("gomita_5", Gomita5Item::new);
		PERRONIGTHMER = register("perronigthmer", PerronigthmerItem::new);
		NAITBEAR_SPAWN_EGG = register("naitbear_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.NAITBEAR.get(), properties));
		SAL_2 = register("sal_2", Sal2Item::new);
		GUMMYBEAR = register("gummybear", GummybearItem::new);
		PINCHOCOMPLETO = register("pinchocompleto", PinchocompletoItem::new);
		CRISTALFUNDIDO = register("cristalfundido", CristalfundidoItem::new);
		CHILEPESADILLA = register("chilepesadilla", ChilepesadillaItem::new);
		HADA_DEDULCE_SPAWN_EGG = register("hada_dedulce_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HADA_DEDULCE.get(), properties));
		CORRINPOPPER_SPAWN_EGG = register("corrinpopper_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.CORRINPOPPER.get(), properties));
		SWETIPOPPER_SPAWN_EGG = register("swetipopper_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.SWETIPOPPER.get(), properties));
		CORRINMETRIC_SPAWN_EGG = register("corrinmetric_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.CORRINMETRIC.get(), properties));
		CUCHILLOFUN = register("cuchillofun", CuchillofunItem::new);
		DUMPLINGS = register("dumplings", DumplingsItem::new);
		TEDEBOBA = register("tedeboba", TedebobaItem::new);
		TEDEBOBAMETRIC = register("tedebobametric", TedebobametricItem::new);
		BANANASPLIT = register("bananasplit", BananasplitItem::new);
		BANANA = register("banana", BananaItem::new);
		SEMILLADEBOBA = register("semilladeboba", SemilladebobaItem::new);
		BOBALIQUIDA = register("bobaliquida", BobaliquidaItem::new);
		DUMPLINGVENDEDORDEBOBA_SPAWN_EGG = register("dumplingvendedordeboba_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINGVENDEDORDEBOBA.get(), properties));
		DUMPLINPEQUENO_SPAWN_EGG = register("dumplinpequeno_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINPEQUENO.get(), properties));
		DUMPLINGMEDIANO_SPAWN_EGG = register("dumplingmediano_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINGMEDIANO.get(), properties));
		DUMPLINGRANDE_SPAWN_EGG = register("dumplingrande_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINGRANDE.get(), properties));
		CALAMARFRITO_SPAWN_EGG = register("calamarfrito_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.CALAMARFRITO.get(), properties));
		SANDWICHSALVAJE_SPAWN_EGG = register("sandwichsalvaje_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.SANDWICHSALVAJE.get(), properties));
		DURIAN = register("durian", DurianItem::new);
		CUBANO_SPAWN_EGG = register("cubano_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.CUBANO.get(), properties));
		SATAANDAGUI = register("sataandagui", SataandaguiItem::new);
		CONODEHELADO_2 = register("conodehelado_2", Conodehelado2Item::new);
		SATAANDAGI = register("sataandagi", SataandagiItem::new);
		GRANADILLAROJA = register("granadillaroja", GranadillarojaItem::new);
		BAOZI = register("baozi", BaoziItem::new);
		YAKI_ONIGIRI = register("yaki_onigiri", YakiOnigiriItem::new);
		SANDWICHDULCE_SPAWN_EGG = register("sandwichdulce_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.SANDWICHDULCE.get(), properties));
		ZONGZI = register("zongzi", ZongziItem::new);
		BOLADESESAMO = register("boladesesamo", BoladesesamoItem::new);
		GREENGRAPES = register("greengrapes", GreengrapesItem::new);
		PURPLEONION = register("purpleonion", PurpleonionItem::new);
		WHITEONION = register("whiteonion", WhiteonionItem::new);
		GOMITA_6 = register("gomita_6", Gomita6Item::new);
		LETTUCE = register("lettuce", LettuceItem::new);
		TOMATO_STAGE_0 = block(MilasAndMetricGastronomyModModBlocks.TOMATO_STAGE_0);
		TOMATO_STAGE_1 = block(MilasAndMetricGastronomyModModBlocks.TOMATO_STAGE_1);
		TOMATO_STAGE_2 = block(MilasAndMetricGastronomyModModBlocks.TOMATO_STAGE_2);
		TOMATO_STAGE_3 = block(MilasAndMetricGastronomyModModBlocks.TOMATO_STAGE_3);
		CANDYGRASS = block(MilasAndMetricGastronomyModModBlocks.CANDYGRASS);
		CANDYBARPLANT = block(MilasAndMetricGastronomyModModBlocks.CANDYBARPLANT);
		OSO_6_SPAWN_EGG = register("oso_6_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.OSO_6.get(), properties));
		HELADOMOB_SPAWN_EGG = register("heladomob_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB.get(), properties));
		HELADOMOB_2_SPAWN_EGG = register("heladomob_2_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_2.get(), properties));
		HELADOMOB_3_SPAWN_EGG = register("heladomob_3_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_3.get(), properties));
		HELADOMOB_4_SPAWN_EGG = register("heladomob_4_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_4.get(), properties));
		HELADOMOB_5_SPAWN_EGG = register("heladomob_5_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_5.get(), properties));
		HELADOMOB_6_SPAWN_EGG = register("heladomob_6_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_6.get(), properties));
		HELADOMOB_7_SPAWN_EGG = register("heladomob_7_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_7.get(), properties));
		HELADOMOB_8_SPAWN_EGG = register("heladomob_8_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_8.get(), properties));
		HELADOMETRIC_SPAWN_EGG = register("heladometric_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMETRIC.get(), properties));
		SLIME_SPAWN_EGG = register("slime_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.SLIME.get(), properties));
		DONASANGUIJUELA_SPAWN_EGG = register("donasanguijuela_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.DONASANGUIJUELA.get(), properties));
		PHATOMPALETA_SPAWN_EGG = register("phatompaleta_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.PHATOMPALETA.get(), properties));
		PHATOMPALETA_2_SPAWN_EGG = register("phatompaleta_2_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.PHATOMPALETA_2.get(), properties));
		JARRON_SPAWN_EGG = register("jarron_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.JARRON.get(), properties));
		JARRONJULIAN_SPAWN_EGG = register("jarronjulian_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.JARRONJULIAN.get(), properties));
		SMORE_SPAWN_EGG = register("smore_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.SMORE.get(), properties));
		SMOREVOLADOR_SPAWN_EGG = register("smorevolador_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.SMOREVOLADOR.get(), properties));
		ARANAHAMBURGUESA_SPAWN_EGG = register("aranahamburguesa_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.ARANAHAMBURGUESA.get(), properties));
		SERPIENTEHELADO_SPAWN_EGG = register("serpientehelado_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.SERPIENTEHELADO.get(), properties));
		PANDEPERRONAITMER = register("pandeperronaitmer", PandeperronaitmerItem::new);
		HELADO_1 = register("helado_1", Helado1Item::new);
		HELADO_2 = register("helado_2", Helado2Item::new);
		HELADO_3 = register("helado_3", Helado3Item::new);
		HELADO_4 = register("helado_4", Helado4Item::new);
		HELADO_5 = register("helado_5", Helado5Item::new);
		HELADO_6 = register("helado_6", Helado6Item::new);
		HELADO_7 = register("helado_7", Helado7Item::new);
		PALETA_1 = register("paleta_1", Paleta1Item::new);
		PALETA_2 = register("paleta_2", Paleta2Item::new);
		SMORECOMIDA = register("smorecomida", SmorecomidaItem::new);
		SMORE_2 = register("smore_2", Smore2Item::new);
		CORN = register("corn", CornItem::new);
		SWEETCORN = register("sweetcorn", SweetcornItem::new);
		DUMPLINGIGANTE_SPAWN_EGG = register("dumplingigante_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINGIGANTE.get(), properties));
		GRANDDUMPLING = register("granddumpling", GranddumplingItem::new);
		BLOQUESERPIENTE = block(MilasAndMetricGastronomyModModBlocks.BLOQUESERPIENTE, new Item.Properties().rarity(Rarity.UNCOMMON));
		ESTATUANAITBEAR = block(MilasAndMetricGastronomyModModBlocks.ESTATUANAITBEAR);
		MALTEADITO_SPAWN_EGG = register("malteadito_spawn_egg", properties -> new SpawnEggItem(MilasAndMetricGastronomyModModEntities.MALTEADITO.get(), properties));
		CUPKAQUEMAJODEFINITIVO = register("cupkaquemajodefinitivo", CupkaquemajodefinitivoItem::new);
		CEREZA = register("cereza", CerezaItem::new);
		CEREZADULCE = register("cerezadulce", CerezadulceItem::new);
		MALTEADA = register("malteada", MalteadaItem::new);
		MALTEADAMETRIC = register("malteadametric", MalteadametricItem::new);
		CREMABATIDA = register("cremabatida", CremabatidaItem::new);
		PIZZACONGELADA = register("pizzacongelada", PizzacongeladaItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static <I extends Item> DeferredItem<I> register(String name, Function<Item.Properties, ? extends I> supplier) {
		return REGISTRY.registerItem(name, supplier, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.registerItem(block.getId().getPath(), prop -> new BlockItem(block.get(), prop), properties);
	}

	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), SALSAMILASFLU_BUCKET.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), SALSAMETRICFLU_BUCKET.get());
	}
}